s3ServerBucket:
  Type: AWS::S3::Bucket
  Properties: 
    BucketName: web-bucket-jason-stuart-12322
    WebsiteConfiguration: 
      IndexDocument: index.html



cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties: 
    Schema:
          - Name: name
            AttributeDataType: String
            Mutable: true
          - Name: birthday
            AttributeDataType: String
            Mutable: true
          - Name: nickname
            AttributeDataType: String
            Mutable: true
    EmailConfiguration: 
      EmailSendingAccount: COGNITO_DEFAULT
    UsernameAttributes: 
      - email
    UserPoolName: "TodoList-dev"

#Cognito Client
cognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties: 
    ClientName: Web
    UserPoolId: !Ref cognitoUserPool









userPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /TodoList/dev/userPoolId
    Type: String
    Value: !GetAtt cognitoUserPool.Arn

userPoolClientParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /TodoList/dev/userPoolClient
    Type: String
    Value: !Ref cognitoUserPoolClient

S3BucketNameParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /TodoList/dev/S3Name
    Type: String
    Value: !Ref  s3ServerBucket