s3ServerBucket:
  Type: AWS::S3::Bucket
  Properties: 
    BucketName: web-bucket-jason-stuart-12322
    WebsiteConfiguration: 
      IndexDocument: index.html
cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties: 
    EmailConfiguration: 
      EmailSendingAccount: COGNITO_DEFAULT
    UsernameAttributes: 
      - email
    UserPoolName: "TodoList-dev"

#Cognito Client
cognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties: 
    ClientName: Web
    UserPoolId: !Ref cognitoUserPool







cognitoIdentityPoolRoleAttachment:
  Type: AWS::Cognito::IdentityPoolRoleAttachment
  Properties: 
    IdentityPoolId: !Ref cognitoIdentityPool
    Roles: 
      unauthenticated: !GetAtt cognitoUnauthIAMRole.Arn
                
cognitoIdentityPool:
  Type: AWS::Cognito::IdentityPool
  Properties: 
    AllowUnauthenticatedIdentities: true
    CognitoIdentityProviders: 
      - ClientId: !Ref cognitoUserPoolClient
        ProviderName: !GetAtt cognitoUserPool.ProviderName
    IdentityPoolName: TodoList-devIdentityPool

userPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /TodoList/dev/userPoolId
    Type: String
    Value: !GetAtt cognitoUserPool.Arn

userPoolClientParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /TodoList/dev/userPoolClient
    Type: String
    Value: !Ref cognitoUserPoolClient

identityPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /TodoList/dev/identityPoolId
    Type: String
    Value: !GetAtt cognitoIdentityPool.Arn

S3BucketNameParam:
  Type: AWS::SSM::Parameter
  Properties:
    Name: /TodoList/dev/S3Name
    Type: String
    Value: !Ref  s3ServerBucket