
service: todo-list-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-2



functions:
  hello:
    handler: handler.hello

resources:
  Resources: ${file(resources.yml)}
